### ISSUE TITLE
core错误依旧

### ISSUE THREAD

**Issue by jiashiwen** [jdcloud-api/jdcloud-sdk-go#34]
jdcloud-api/jdcloud-sdk-go/core/Signer.go:170:11: assignment mismatch: 2 variables but 1 values

仔细看了一下Signer.go以及它调用的github.com/satori/go.uuid，uuid.NewV4()返回一个参数但，Signer.go中接收参数为２，

**Comment by oulinbao** [comment]
https://github.com/satori/go.uuid/blob/master/generator.go
使用master分支的接口

**Comment by jiashiwen** [comment]
补充一下，我的项目是用dep做依赖关系。Gopkg.toml这样编写
```
required = ["github.com/satori/go.uuid"]
[[constraint]]
 branch = "master"
 name = "github.com/satori/go.uuid"
```
```
dep ensure --update
```
