### ISSUE TITLE
错误返回方式修改

### ISSUE THREAD

**Issue by lidaobing** [jdcloud-api/jdcloud-sdk-go#5]
https://github.com/jdcloud-api/jdcloud-sdk-go/blob/3506604829d500b29a8fc936ec7cab24cd4cfaa8/services/oss/client/OssClient.go#L68

```go
    jdResp := &PutBucketResponse{}
    err = json.Unmarshal(resp, jdResp)
    return jdResp, err
```
改为 
```go
    jdResp := &PutBucketResponse{}
    err = json.Unmarshal(resp, jdResp)
    if err != nil {
        return nil, err
    }
    return jdResp, err
```

**Comment by oulinbao** [comment]
https://github.com/jdcloud-api/jdcloud-sdk-go/commit/365378ff9bf06ef3020e6ab0d73602fe5e521161
已修改
