### ISSUE TITLE
需要切换依赖的 uuid 包

### ISSUE THREAD

**Issue by lidaobing** [jdcloud-api/jdcloud-sdk-go#67]
```
$ go1.12.5 run monitor.go 
# github.com/jdcloud-api/jdcloud-sdk-go/core
../../../go/pkg/mod/github.com/jdcloud-api/jdcloud-sdk-go@v1.9.0/core/Signer.go:170:11: assignment mismatch: 2 variables but uuid.NewV4 returns 1 values
```

原因:
1. go 1.11之后推荐使用 go mod 来管理你的包，go mod 会优先寻找稳定版，即 tag 好的版本
2. go.uuid 包的稳定版本和master版本接口不一致
3. 建议切换到 https://github.com/gofrs/uuid

**Comment by zwen-lab** [comment]
1.使用go mod来管理包，确实有这个问题。
2.暂时先这样处理  GO111MODULE=on go get github.com/satori/go.uuid@master
3. go get 指定master ,不管package有没有打tag，都会选择master分支的最新commit
4. 执行后 go.mod已经更新了。 
github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b // indirect
